export const FETCH_MOVIES = "FETCH_MOVIES"
export const FETCH_REC = "FETCH_REC"
export const DELETE_MYLIST = "DELETE_MYLIST"
export const PUSH_REC = "PUSH_REC"
export const DELETE_REC = "DELETE_REC"
export const PUSH_MYLIST = "PUSH_MYLIST"
